version: "3"

services:
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - "5433:5433"
    command: -p 5433
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    networks:
      - api

  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=12345678
      - REDIS_PORT=6379
    ports:
      - "6380:6379"
    networks:
      - api

  api:
    build:
      context: .
    entrypoint: yarn start:dev
    environment:
      - REDIS_HOST=redis
      - PORT=8002
      - DATABASE_PORT=5433
      - DATABASE_USER=prisma
      - DATABASE_HOST=postgres
      - DATABASE_PASSWORD=prisma
      - DATABASE_URL=postgresql://prisma:prisma@postgres:5433
    ports:
      - "8002:8000"
      - "8003:8001"
    networks:
      - api
      - loki
  loki:
    image: grafana/loki:2.6.0
    ports:
      - "3101:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.6.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki


networks:
  api:
  loki: