server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://242422:eyJrIjoiZWY5NjFmNWJlYzI1MGU0ZGM4OGNkY2Y1ZGJkZGQ1MDk2ZTE2MjgxZiIsIm4iOiJ0ZXN0IiwiaWQiOjY3Mjc4OH0=@logs-prod-eu-west-0.grafana.net/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log
