name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: HatsuneMiku3939/direnv-action@v1

      - run: docker-compose up -d postgres redis
      - run: npm ci
      - run: npm run db:up
      - run: echo $DATABASE_URL
      - run: npm start &
      - run: while curl -s localhost:8000 >/dev/null; do sleep 2; done
      - run: npm run test
